### PR TITLE
Fix problem with missing gem specs

### LINKED ISSUE #208: tapioca sync fails because of nokogiri native gem having different dependencies than compiled gem
Essentially, this error occurs when I run `bundle exec tapioca sync` on my Rails app [vglist](https://github.com/connorshea/vglist):

```
Connors-MacBook-Pro-2:vglist connorshea$ bundle exec tapioca sync
Removing RBI files of gems that have been removed:

bundler: failed to load command: tapioca (/Users/connorshea/.rbenv/versions/2.7.2/bin/tapioca)
Traceback (most recent call last):
	44: from /Users/connorshea/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
	43: from /Users/connorshea/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
	42: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/exe/bundle:37:in `<top (required)>'
	41: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	40: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/exe/bundle:49:in `block in <top (required)>'
	39: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli.rb:24:in `start'
	38: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	37: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli.rb:30:in `dispatch'
	36: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	35: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	34: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	33: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli.rb:497:in `exec'
	32: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:28:in `run'
	31: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
	30: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/cli/exec.rb:63:in `load'
	29: from /Users/connorshea/.rbenv/versions/2.7.2/bin/tapioca:23:in `<top (required)>'
	28: from /Users/connorshea/.rbenv/versions/2.7.2/bin/tapioca:23:in `load'
	27: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.13/exe/tapioca:6:in `<top (required)>'
	26: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	25: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	24: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	23: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	22: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.13/lib/tapioca/cli.rb:92:in `sync'
	21: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.13/lib/tapioca.rb:10:in `silence_warnings'
	20: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/user_interaction.rb:46:in `use_ui'
	19: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.13/lib/tapioca.rb:11:in `block in silence_warnings'
	18: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.13/lib/tapioca/cli.rb:93:in `block in sync'
	17: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6189/lib/types/private/methods/_methods.rb:233:in `block in _on_method_added'
	16: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6189/lib/types/private/methods/_methods.rb:233:in `call'
	15: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.13/lib/tapioca/generator.rb:149:in `sync_rbis_with_gemfile'
	14: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6189/lib/types/private/methods/_methods.rb:233:in `block in _on_method_added'
	13: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6189/lib/types/private/methods/_methods.rb:233:in `call'
	12: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.13/lib/tapioca/generator.rb:332:in `perform_removals'
	11: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6189/lib/types/private/methods/_methods.rb:233:in `block in _on_method_added'
	10: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6189/lib/types/private/methods/_methods.rb:233:in `call'
	 9: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.13/lib/tapioca/generator.rb:298:in `removed_rbis'
	 8: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6189/lib/types/private/methods/_methods.rb:233:in `block in _on_method_added'
	 7: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6189/lib/types/private/methods/_methods.rb:233:in `call'
	 6: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.13/lib/tapioca/generator.rb:270:in `expected_rbis'
	 5: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6189/lib/types/private/methods/_methods.rb:233:in `block in _on_method_added'
	 4: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.5.6189/lib/types/private/methods/_methods.rb:233:in `call'
	 3: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/tapioca-0.4.13/lib/tapioca/gemfile.rb:35:in `dependencies'
	 2: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/spec_set.rb:81:in `materialize'
	 1: from /Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/spec_set.rb:81:in `map!'
/Users/connorshea/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.3/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find mini_portile2-2.5.0 in any of the sources (Bundler::GemNotFound)
```

I tried upgrading RubyGems, upgrading Bundler, upgrading Sorbet, downgrading Tapioca from `0.4.13` to `0.4.10`, running `bundle pristine` to reinstall absolutely every gem in my Gemfile, and none of it changed anything. It occurs on both Bundler 2.2.3 and 2.2.5.

The only thing that fixed it was downgrading nokogiri from 1.11.1 to 1.10.10, which removes the native gem differentiation.

I suspect it has to do with this, nokogiri 'proper' requiring mini_portile2 but its native versions not?:

```
    nokogiri (1.11.1)
      mini_portile2 (~> 2.5.0)
      racc (~> 1.4)
    nokogiri (1.11.1-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.11.1-x86_64-linux)
      racc (~> 1.4)
```

It looks like it's an intentional choice by Nokogiri, because mini_portile2 is required to compile nokogiri, but if you have a pre-compiled version there's no reason to install it: https://github.com/sparklemotion/nokogiri/issues/2078

So that'd explain why we don't have the gem locally on macOS. I suspect we need to figure out a way to filter out gems that wouldn't exist locally?

### PR DESCRIPTION
**Pull request by paracycle**
### Motivation

Fix #208.

### Implementation

`Bundler::SpecSet#materialize` has an optional extra parameter that can be supplied an array, which will be used to collect the names of the missing gem specs when materializing. This prevents missing gem specs from raising errors, so by passing an empty array for this parameter, we can prevent Tapioca from crashing when it runs into missing specs for dependencies that don't make sense for the current platform.

### Tests

Added a `nokogiri` dependency on the test repo and added a test to ensure that its optional dependency does not get processed.

### CODE REVIEW

File: lib/tapioca/gemfile.rb [hunk 1]
```diff
@@ -30,9 +30,12 @@ def dependencies
       @dependencies ||= begin
         specs = definition.locked_gems.specs.to_a
 
+        # TODO: Somehow display these missing specs to the user?!
+        missing_specs = Array.new # rubocop:disable Style/EmptyLiteral
```
Comment (Morriar) [inline lib/tapioca/gemfile.rb:34]: Log them into a file and display the path to the log file in case of errors?

File: spec/support/repo/Gemfile [hunk 2]
```diff
@@ -19,3 +19,5 @@ gem("smart_properties")
 gem("activesupport")
 # Needed to test Git gems
 gem("ast", git: "https://github.com/whitequark/ast", ref: "e07a4f66e05ac7972643a8841e336d327ea78ae1")
+# Needed to test missing gems
+gem("nokogiri", ">= 1.11.1")
```
Comment (Morriar) [inline spec/support/repo/Gemfile:23]: Not sure if the 2.4 failures are related or not: https://github.com/Shopify/tapioca/pull/213/checks?check_run_id=1765659365 maybe a conflict with the `ast` version required the line before?

Maybe the command logged the failures in a file somewhere and we can check 🤯

**Review by Morriar — APPROVED** [review]

File: lib/tapioca/gemfile.rb (hunk 1 above)
Comment (paracycle) [reply lib/tapioca/gemfile.rb:34]: Yeah, will probably be something like that. I added the TODO so that I don't have to think about that right now.

File: spec/support/repo/Gemfile (hunk 2 above)
Comment (paracycle) [reply spec/support/repo/Gemfile:23]: Yeap, indeed that was the problem:
```
$ bundle
Fetching https://github.com/whitequark/ast
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    nokogiri (>= 1.11.1) was resolved to 1.11.1, which depends on
      ruby (>= 2.5.0)

    tapioca was resolved to 0.4.13, which depends on
      ruby (>= 2.4)
```
I will need to skip this dependency on Ruby 2.4. At least the test won't break since it tests the absence of the RBI generation 😅

File: lib/tapioca/gemfile.rb (hunk 1 above)
Comment (paracycle) [reply lib/tapioca/gemfile.rb]: Well, actually, I went ahead and refactored this so that I can print missing specs on the screen.

File: Gemfile [hunk 3]
```diff
@@ -10,7 +10,7 @@ group(:deployment, :development) do
   gem("rake")
 end
 
-gem("bundler", "~> 1.17")
+gem("bundler", ">= 2")
```
Comment (rafaelfranca) [inline Gemfile:13]: Should not bundler be in the gemspec since it is a runtime dependency? Can tapioca run without bundler being installed?

Comment (paracycle) [reply Gemfile:13]: Ooops, that's correct. Fixing it now.

**Review by rafaelfranca — APPROVED** [review]

File: lib/tapioca/gemfile.rb [hunk 4]
```diff
@@ -55,6 +51,23 @@ def require
     sig { returns(File) }
     attr_reader(:gemfile, :lockfile)
 
+    sig { returns([T::Array[Gem], T::Array[String]]) }
+    def load_dependencies
+      specs = definition.locked_gems.specs.to_a
+
+      missing_specs = T::Array[String].new
```
Comment (Morriar) [inline lib/tapioca/gemfile.rb:58]:
```suggestion
      missing_specs.clear
```

File: spec/template_helper.rb [hunk 5]
```diff
@@ -5,31 +5,21 @@
...
   def template(src)
-    erb = if ErbBinding::ERB_SUPPORTS_KVARGS
+    erb = if ERB_SUPPORTS_KVARGS
       ::ERB.new(src, trim_mode: ">")
     else
       ::ERB.new(src, nil, ">")
     end
 
-    erb.result(ErbBinding.new.erb_bindings)
+    erb.result(instance_exec { binding })
```
Comment (Morriar) [inline spec/template_helper.rb:23]: Because `binding` is private?

**Review by Morriar — APPROVED** [review]

File: lib/tapioca/gemfile.rb (hunk 4 above)
Comment (paracycle) [reply lib/tapioca/gemfile.rb:58]: this is just a local variable.

Comment (Morriar) [reply lib/tapioca/gemfile.rb:58]: 🤦

File: spec/template_helper.rb (hunk 5 above)
Comment (paracycle) [reply spec/template_helper.rb]: No, it is left-over code. Removing...
