### PR TITLE
Fix parameter handling in signatures

### LINKED ISSUE #116: srb tc error: Bad parameter ordering
Hi, 

with the following gemfile:

``` ruby
gem "sorbet"
gem "tapioca", "0.4.4"
gem "spoom", "1.0.4"
```

it installs these other deps, (but I don’t think this is relevant):
<details>
```
Using ast 2.4.1
Using bundler 2.1.4
Using sorbet-runtime 0.5.5881
Using coderay 1.1.3
Using highline 2.0.3
Using method_source 1.0.0
Using rainbow 3.0.0
Using colorize 0.8.1
Using sorbet-static 0.5.5881 (universal-darwin-19)
Using thor 1.0.1
Using sorbet 0.5.5881
Using pry 0.13.1
Using parser 2.7.1.4
Using commander 4.5.2
Using parlour 4.0.1
Using spoom 1.0.4
Using tapioca 0.4.4
```
</details>

It appears that the generated rbi for "spoom" is not valid: (I'm not sure what this gem is, just some transitive dependency for me)

``` ruby
bundle exec srb tc .
sorbet/rbi/gems/spoom@1.0.4.rbi:275: Bad parameter ordering for arg, expected path instead https://srb.help/5049
     275 |    def srb(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                       ^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:274: Expected index in signature:
     274 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns([String, T::Boolean]) }
                           ^^^^

sorbet/rbi/gems/spoom@1.0.4.rbi:275: Bad parameter ordering for path, expected capture_err instead https://srb.help/5049
     275 |    def srb(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                            ^^^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:274: Expected index in signature:
     274 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns([String, T::Boolean]) }
                                         ^^^^^^^^^^^

sorbet/rbi/gems/spoom@1.0.4.rbi:275: Bad parameter ordering for capture_err, expected arg instead https://srb.help/5049
     275 |    def srb(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                                                 ^^^^^^^^^^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:274: Expected index in signature:
     274 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns([String, T::Boolean]) }
                                                                  ^^^

sorbet/rbi/gems/spoom@1.0.4.rbi:279: Bad parameter ordering for arg, expected path instead https://srb.help/5049
     279 |    def srb_metrics(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                               ^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:278: Expected index in signature:
     278 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns(T.nilable(Spoom::Sorbet::Metrics)) }
                           ^^^^

sorbet/rbi/gems/spoom@1.0.4.rbi:279: Bad parameter ordering for path, expected capture_err instead https://srb.help/5049
     279 |    def srb_metrics(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                                    ^^^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:278: Expected index in signature:
     278 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns(T.nilable(Spoom::Sorbet::Metrics)) }
                                         ^^^^^^^^^^^

sorbet/rbi/gems/spoom@1.0.4.rbi:279: Bad parameter ordering for capture_err, expected arg instead https://srb.help/5049
     279 |    def srb_metrics(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                                                         ^^^^^^^^^^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:278: Expected index in signature:
     278 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns(T.nilable(Spoom::Sorbet::Metrics)) }
                                                                  ^^^

sorbet/rbi/gems/spoom@1.0.4.rbi:281: Bad parameter ordering for arg, expected path instead https://srb.help/5049
     281 |    def srb_tc(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                          ^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:280: Expected index in signature:
     280 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns([String, T::Boolean]) }
                           ^^^^

sorbet/rbi/gems/spoom@1.0.4.rbi:281: Bad parameter ordering for path, expected capture_err instead https://srb.help/5049
     281 |    def srb_tc(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                               ^^^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:280: Expected index in signature:
     280 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns([String, T::Boolean]) }
                                         ^^^^^^^^^^^

sorbet/rbi/gems/spoom@1.0.4.rbi:281: Bad parameter ordering for capture_err, expected arg instead https://srb.help/5049
     281 |    def srb_tc(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                                                    ^^^^^^^^^^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:280: Expected index in signature:
     280 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns([String, T::Boolean]) }
                                                                  ^^^

sorbet/rbi/gems/spoom@1.0.4.rbi:283: Bad parameter ordering for arg, expected path instead https://srb.help/5049
     283 |    def srb_version(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                               ^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:282: Expected index in signature:
     282 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns(T.nilable(String)) }
                           ^^^^

sorbet/rbi/gems/spoom@1.0.4.rbi:283: Bad parameter ordering for path, expected capture_err instead https://srb.help/5049
     283 |    def srb_version(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                                    ^^^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:282: Expected index in signature:
     282 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns(T.nilable(String)) }
                                         ^^^^^^^^^^^

sorbet/rbi/gems/spoom@1.0.4.rbi:283: Bad parameter ordering for capture_err, expected arg instead https://srb.help/5049
     283 |    def srb_version(*arg, path: T.unsafe(nil), capture_err: T.unsafe(nil)); end
                                                         ^^^^^^^^^^^^
    sorbet/rbi/gems/spoom@1.0.4.rbi:282: Expected index in signature:
     282 |    sig { params(path: String, capture_err: T::Boolean, arg: String).returns(T.nilable(String)) }
                                                                  ^^^
Errors: 12
```

I can work around this by using my old rbi for spoom, since I don’t use it directly so it shouldn't matter much, but I figured it'd be good to report this.

### PR DESCRIPTION
**Pull request by paracycle**
## Motivation

Fixes #116

There were a couple of problems with parameter handling in signatures:

1. We were messing up the parameter ordering in the signature which sometimes ended up not matching with the order in which parameters were declared in the method parameter list. 
2. We were skipping `keyrest` arguments completely. :facepalm:

## Implementation

The main problem is fixed by iterating over the actual method parameters and only using signature parameter mapping as a lookup table to get the relevant type for the parameter. I had to keep a sanitized version of the parameter list to pass to the signature compile step, since we end up modifying the parameter names while generating the method definition. The parameter name in the signature should match that changed name, so the sanitized parameter list should be used when processing the signatures.

### CODE REVIEW

File: lib/tapioca/compilers/symbol_table/symbol_generator.rb [hunk 1]
```diff
@@ -546,25 +552,31 @@ def compile_method(symbol_name, constant, method)
...
 
-        sig { params(signature: T.untyped).returns(String) }
-        def compile_signature(signature)
-          params = signature.arg_types
-          params += signature.kwarg_types.to_a
-          params << [signature.rest_name, signature.rest_type] if signature.has_rest
-          params << [signature.block_name, signature.block_type] if signature.block_name
+        sig { params(signature: T.untyped, parameters: T::Array[[Symbol, String]]).returns(String) }
+        def compile_signature(signature, parameters)
+          parameter_types = T.let(signature.arg_types, T::Array[[Symbol, T::Types::Base]])
```
Comment (Morriar) [inline lib/tapioca/compilers/symbol_table/symbol_generator.rb:568]: Why not directly composing a hash instead of an array of arrays that is then translated into a hash?

Comment (paracycle) [reply lib/tapioca/compilers/symbol_table/symbol_generator.rb]: Good call, done!
