### PR TITLE
Make sure we use compare by identity `Set`s properly

### LINKED ISSUE #1728: `bin/tapioca dsl` fails with `undefined method `ancestors' for ...`
This is the exact line that is throwing `tapioca` off: https://github.com/astroband/ruby-stellar-sdk/blob/main/base/lib/stellar/ext/xdr.rb#L30

I've attempted to ignore the gem, but the ignore is not being respected:
```yml
# sorbet/tapioca/config.yml
annotations:
  typed_overrides:
    stellar: "ignore"
    stellar-base: "ignore"
gem:
  exclude:
    - "stellar-base"
    - "stellar"
```
```
~/workspace/monorail - master $ bin/tapioca dsl
Loading DSL extension classes... Done
Loading Rails application... Done
Loading DSL compiler classes... Done
Compiling DSL RBI files...

/Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/stellar-base-0.32.0/lib/stellar/ext/xdr.rb:30:in `block (2 levels) in <main>': undefined method `ancestors' for #<XDR::Opaque:0x000000010e590650 @length=32, @padding=0> (NoMethodError)

      elsif value_type.ancestors.include?(XDR::Struct)
                      ^^^^^^^^^^
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/3.2.0/set.rb:522:in `[]='
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/3.2.0/set.rb:522:in `add'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/3.2.0/set.rb:609:in `block in merge'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/3.2.0/set.rb:276:in `each'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/3.2.0/set.rb:276:in `each_entry'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/3.2.0/set.rb:276:in `do_with_enum'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/3.2.0/set.rb:609:in `merge'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/3.2.0/set.rb:253:in `initialize'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/types/typed_set.rb:37:in `new'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/types/typed_set.rb:37:in `new'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/lib/tapioca/dsl/compiler.rb:39:in `processable_constants'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/lib/tapioca/dsl/pipeline.rb:133:in `map'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/lib/tapioca/dsl/pipeline.rb:133:in `gather_constants'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/lib/tapioca/dsl/pipeline.rb:59:in `run'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/lib/tapioca/commands/abstract_dsl.rb:73:in `generate_dsl_rbi_files'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/lib/tapioca/commands/dsl_generate.rb:16:in `execute'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/lib/tapioca/commands/command.rb:27:in `block in run'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/lib/tapioca.rb:23:in `block in silence_warnings'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/user_interaction.rb:47:in `use_ui'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/lib/tapioca.rb:22:in `silence_warnings'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/lib/tapioca/commands/command.rb:26:in `run'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `bind_call'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/lib/tapioca/cli.rb:168:in `dsl'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/base.rb:584:in `start'
        from /Users/alexevanczuk/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/tapioca-0.11.10/exe/tapioca:25:in `<top (required)>'
        from bin/tapioca:29:in `load'
        from bin/tapioca:29:in `<main>'
```

Thanks for your help!

### PR DESCRIPTION
**Pull request by paracycle**
### Motivation

Fix #1728 

### Implementation

There were a few places where we have not been using `Set`s with `compare_by_identity` properly. This commit fixes those instances so that the test added in the previous commit passes.

### Tests

Added a failing test that passes with the fix.

### CODE REVIEW

**Review by Morriar — APPROVED** [review]

File: lib/tapioca/dsl/compiler.rb [hunk 1]
```diff
@@ -36,7 +36,7 @@ def gather_constants; end
         sig { returns(T::Set[Module]) }
         def processable_constants
           @processable_constants ||= T.let(
-            T::Set[Module].new(gather_constants).compare_by_identity,
+            T::Set[Module].new.compare_by_identity.merge(gather_constants),
```
Comment (amomchilov) [inline lib/tapioca/dsl/compiler.rb:39]: Is this some kind of perf optimization?
